version: "3.9"

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    container_name: habr_parser
    volumes:
      - ./:/app
    command: "python3 /app/run.py"
    networks:
      - habr_p_net
  
  database:
    image: "postgres:16"
    container_name: habr_parser_db
    volumes:
      - habr_pg_db:/var/lib/postgresql/data
      - ./docker/pgsql/.bashrc:/root/.bashrc
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    expose:
      - 3306
    networks:
      - habr_p_net

networks:
  habr_p_net:
    driver: bridge

volumes:
  habr_pg_db:
    external: true